package shared

import "github.com/vladolaru/cabrero/internal/tui/message"

// HelpEntry is a single key binding with a full description.
type HelpEntry struct {
	Key  string // display text, e.g. "a" or "j/↓"
	Desc string // full description, e.g. "Approve this proposal and apply the change"
}

// HelpSection groups related help entries under a title.
type HelpSection struct {
	Title   string
	Entries []HelpEntry
}

// HelpContent bundles a view title, description, and key binding sections.
type HelpContent struct {
	Title       string
	Description string
	Sections    []HelpSection
}

// HelpForView returns help content (title, description, and key binding sections) for the given view.
func HelpForView(view message.ViewState, km KeyMap) HelpContent {
	switch view {
	case message.ViewDashboard:
		return HelpContent{
			Title: "Dashboard Help",
			Description: "The dashboard is the home view. It lists proposals and fitness " +
				"reports waiting for your review. Each row shows a type indicator " +
				"(● proposal, ◎ fitness report), the proposal type, target file path, " +
				"and confidence level.\n\n" +
				"Proposals are skill improvements generated by the pipeline from " +
				"real Claude Code session data. Approving a proposal blends the " +
				"change into the target file — you see a before/after diff for " +
				"final confirmation before anything is written. Rejecting archives " +
				"the proposal and feeds the rejection back as calibration signal. " +
				"Deferring archives the proposal for later — it won't reappear.\n\n" +
				"Every approved change is recorded with a rollback entry, so any " +
				"change Cabrero has applied can be undone from the Source Manager.\n\n" +
				"Fitness reports appear for sources in EVALUATE mode (typically " +
				"third-party plugins you don't own). Instead of proposing changes, " +
				"the pipeline assesses whether the source is helping or causing " +
				"friction — informing whether to keep, replace, or supplement it.",
			Sections: dashboardHelp(km),
		}
	case message.ViewProposalDetail:
		return HelpContent{
			Title: "Proposal Detail Help",
			Description: "Shows the full context for a single proposal: the proposed " +
				"diff, the evaluator's rationale, and the citation chain linking " +
				"the proposal back to raw session turns.\n\n" +
				"Open the AI chat panel to ask questions about the proposal, " +
				"request a more conservative version, or understand the risk of " +
				"approving. Revised diffs produced in chat can be approved instead " +
				"of the original — both versions are tracked with full provenance.\n\n" +
				"Approving invokes the claude CLI with the writing skill loaded, " +
				"so changes blend into the existing file matching its tone and " +
				"structure. You see the final before/after diff for confirmation " +
				"before the write is committed.",
			Sections: detailHelp(km),
		}
	case message.ViewFitnessDetail:
		return HelpContent{
			Title: "Fitness Report Help",
			Description: "Fitness reports are generated for sources in EVALUATE mode. " +
				"This mode is for sources you don't own — typically third-party " +
				"plugins. Instead of proposing changes (which would be inappropriate " +
				"for code you don't maintain), the pipeline assesses whether the " +
				"source is helping or causing friction in your sessions.\n\n" +
				"The report shows a three-category health breakdown: sessions where " +
				"the source was followed correctly, worked around, or caused " +
				"confusion. Each category has expandable session evidence so you " +
				"can inspect the underlying data.\n\n" +
				"Use this to decide whether to keep the source as-is, supplement " +
				"it with a user-level skill you own, or stop using it entirely. " +
				"Dismissing archives the report.",
			Sections: fitnessHelp(km),
		}
	case message.ViewSourceManager:
		return HelpContent{
			Title: "Source Manager Help",
			Description: "Lists all tracked sources (skills, commands, agents, CLAUDE.md " +
				"files) grouped by origin. Each source has an ownership " +
				"classification (mine/not mine) and an approach (iterate/evaluate) " +
				"that determines how the pipeline processes it.\n\n" +
				"Sources you own use ITERATE mode — the pipeline proposes " +
				"improvements as diffs for your approval. Sources you don't own " +
				"use EVALUATE mode — the pipeline produces fitness assessments " +
				"instead. Unclassified sources are paused until you set their " +
				"ownership.\n\n" +
				"Groups can be collapsed and expanded with the left/right keys.",
			Sections: sourcesHelp(km),
		}
	case message.ViewSourceDetail:
		return HelpContent{
			Title: "Source Detail Help",
			Description: "Shows detailed information for a single source: its origin, " +
				"ownership, approach, session count, health score, and when it was " +
				"last classified.\n\n" +
				"Below the info section, recent changes lists all proposals that " +
				"have been approved or rejected for this source. You can rollback " +
				"the most recent approved change to restore the previous file " +
				"content — every approved change stores a verbatim backup.",
			Sections: sourceDetailHelp(km),
		}
	case message.ViewPipelineMonitor:
		return HelpContent{
			Title: "Pipeline Monitor Help",
			Description: "Shows the operational state of the Cabrero daemon: whether " +
				"it's running, its configuration (poll interval, stale scan, " +
				"inter-session delay), and store metrics (path, session count, " +
				"disk usage).\n\n" +
				"The Recent Runs section lists pipeline executions with per-stage " +
				"timing (parse, classifier, evaluator), status, and project. The " +
				"Activity section shows aggregate token usage and cost. Prompt " +
				"versions track which prompts are active. Data auto-refreshes " +
				"every 5 seconds.\n\n" +
				"Failed runs can be retried. The log viewer shows the full daemon " +
				"log for debugging.",
			Sections: pipelineHelp(km),
		}
	case message.ViewLogViewer:
		return HelpContent{
			Title: "Log Viewer Help",
			Description: "Displays the daemon log as structured, colored entries. " +
				"Each entry shows a timestamp, level badge (INFO, ERROR), and " +
				"message. Multi-line entries (stack traces, continuation lines) " +
				"are collapsed by default with a [+N] indicator.\n\n" +
				"Search finds text across all entries, including collapsed content. " +
				"Matching collapsed entries auto-expand so you can see the context. " +
				"Follow mode auto-scrolls to new entries as they arrive — useful " +
				"for watching the daemon process sessions in real time.",
			Sections: logViewerHelp(km),
		}
	default:
		return HelpContent{
			Title: "Dashboard Help",
			Description: "The dashboard is the home view. It lists proposals and fitness " +
				"reports waiting for your review.",
			Sections: dashboardHelp(km),
		}
	}
}

func dashboardHelp(km KeyMap) []HelpSection {
	return []HelpSection{
		{
			Title: "Navigation",
			Entries: []HelpEntry{
				{km.Up.Help().Key, "Move cursor up"},
				{km.Down.Help().Key, "Move cursor down"},
				{km.HalfPageUp.Help().Key, "Scroll up half a page"},
				{km.HalfPageDown.Help().Key, "Scroll down half a page"},
				{km.GotoTop.Help().Key, "Jump to first item"},
				{km.GotoBottom.Help().Key, "Jump to last item"},
			},
		},
		{
			Title: "Actions",
			Entries: []HelpEntry{
				{km.Open.Help().Key, "Open the selected proposal"},
				{km.Approve.Help().Key, "Approve and apply the selected proposal"},
				{km.Reject.Help().Key, "Reject the selected proposal"},
				{km.Defer.Help().Key, "Defer the selected proposal for later"},
				{km.Filter.Help().Key, "Filter proposals by text"},
				{km.Sort.Help().Key, "Cycle sort order"},
			},
		},
		{
			Title: "Views",
			Entries: []HelpEntry{
				{km.Sources.Help().Key, "Open source manager"},
				{km.Pipeline.Help().Key, "Open pipeline monitor"},
			},
		},
		{
			Title: "Global",
			Entries: []HelpEntry{
				{km.Help.Help().Key, "Toggle this help overlay"},
				{km.Quit.Help().Key, "Quit the application"},
				{km.ForceQuit.Help().Key, "Force quit immediately"},
			},
		},
	}
}

func detailHelp(km KeyMap) []HelpSection {
	return []HelpSection{
		{
			Title: "Navigation",
			Entries: []HelpEntry{
				{km.Up.Help().Key, "Scroll up"},
				{km.Down.Help().Key, "Scroll down"},
				{km.HalfPageUp.Help().Key, "Scroll up half a page"},
				{km.HalfPageDown.Help().Key, "Scroll down half a page"},
				{km.GotoTop.Help().Key, "Jump to top"},
				{km.GotoBottom.Help().Key, "Jump to bottom"},
			},
		},
		{
			Title: "Actions",
			Entries: []HelpEntry{
				{km.Approve.Help().Key, "Approve and apply this proposal"},
				{km.Reject.Help().Key, "Reject this proposal"},
				{km.Defer.Help().Key, "Defer this proposal for later"},
			},
		},
		{
			Title: "Citations",
			Entries: []HelpEntry{
				{km.Up.Help().Key + "/" + km.Down.Help().Key, "Navigate citations (scroll at boundary)"},
				{km.CitationToggle.Help().Key, "Expand/collapse citation"},
			},
		},
		{
			Title: "Detail",
			Entries: []HelpEntry{
				{km.Chat.Help().Key, "Toggle AI chat panel"},
				{km.UseRevision.Help().Key, "Use a specific revision"},
				{km.Chip1.Help().Key, "Quick prompt: why was this flagged?"},
				{km.Chip2.Help().Key, "Quick prompt: show the raw turns"},
				{km.Chip3.Help().Key, "Quick prompt: conservative version"},
				{km.Chip4.Help().Key, "Quick prompt: risk of approving?"},
			},
		},
		{
			Title: "Panes",
			Entries: []HelpEntry{
				{km.TabForward.Help().Key, "Switch to next pane"},
				{km.TabBackward.Help().Key, "Switch to previous pane"},
			},
		},
		{
			Title: "Global",
			Entries: []HelpEntry{
				{km.Back.Help().Key, "Return to dashboard"},
				{km.Help.Help().Key, "Toggle this help overlay"},
				{km.Quit.Help().Key, "Quit the application"},
				{km.ForceQuit.Help().Key, "Force quit immediately"},
			},
		},
	}
}

func fitnessHelp(km KeyMap) []HelpSection {
	return []HelpSection{
		{
			Title: "Navigation",
			Entries: []HelpEntry{
				{km.Up.Help().Key, "Scroll up"},
				{km.Down.Help().Key, "Scroll down"},
				{km.HalfPageUp.Help().Key, "Scroll up half a page"},
				{km.HalfPageDown.Help().Key, "Scroll down half a page"},
				{km.GotoTop.Help().Key, "Jump to top"},
				{km.GotoBottom.Help().Key, "Jump to bottom"},
			},
		},
		{
			Title: "Actions",
			Entries: []HelpEntry{
				{km.Open.Help().Key, "Expand/collapse evidence group"},
				{km.Dismiss.Help().Key, "Dismiss this report"},
			},
		},
		{
			Title: "Views",
			Entries: []HelpEntry{
				{km.Sources.Help().Key, "Open source manager"},
				{km.Chat.Help().Key, "Open AI chat about this report"},
			},
		},
		{
			Title: "Global",
			Entries: []HelpEntry{
				{km.Back.Help().Key, "Return to dashboard"},
				{km.Help.Help().Key, "Toggle this help overlay"},
				{km.Quit.Help().Key, "Quit the application"},
				{km.ForceQuit.Help().Key, "Force quit immediately"},
			},
		},
	}
}

func sourcesHelp(km KeyMap) []HelpSection {
	return []HelpSection{
		{
			Title: "Navigation",
			Entries: []HelpEntry{
				{km.Up.Help().Key, "Move cursor up"},
				{km.Down.Help().Key, "Move cursor down"},
				{km.Left.Help().Key, "Collapse group"},
				{km.Right.Help().Key, "Expand group"},
			},
		},
		{
			Title: "Actions",
			Entries: []HelpEntry{
				{km.Open.Help().Key, "Open source detail / toggle group"},
				{km.ToggleApproach.Help().Key, "Toggle approach (iterate/evaluate)"},
				{km.SetOwnership.Help().Key, "Set ownership (mine/not-mine)"},
			},
		},
		{
			Title: "Views",
			Entries: []HelpEntry{
				{km.Pipeline.Help().Key, "Open pipeline monitor"},
			},
		},
		{
			Title: "Global",
			Entries: []HelpEntry{
				{km.Back.Help().Key, "Return to previous view"},
				{km.Help.Help().Key, "Toggle this help overlay"},
				{km.Quit.Help().Key, "Quit the application"},
				{km.ForceQuit.Help().Key, "Force quit immediately"},
			},
		},
	}
}

func sourceDetailHelp(km KeyMap) []HelpSection {
	return []HelpSection{
		{
			Title: "Actions",
			Entries: []HelpEntry{
				{km.SetOwnership.Help().Key, "Set ownership (mine/not-mine)"},
				{km.ToggleApproach.Help().Key, "Toggle approach (iterate/evaluate)"},
				{km.Rollback.Help().Key, "Rollback latest change"},
			},
		},
		{
			Title: "Global",
			Entries: []HelpEntry{
				{km.Back.Help().Key, "Return to source list"},
				{km.Help.Help().Key, "Toggle this help overlay"},
				{km.Quit.Help().Key, "Quit the application"},
				{km.ForceQuit.Help().Key, "Force quit immediately"},
			},
		},
	}
}

func pipelineHelp(km KeyMap) []HelpSection {
	return []HelpSection{
		{
			Title: "Navigation",
			Entries: []HelpEntry{
				{km.Up.Help().Key, "Move cursor up"},
				{km.Down.Help().Key, "Move cursor down"},
			},
		},
		{
			Title: "Actions",
			Entries: []HelpEntry{
				{km.Open.Help().Key, "Open run detail"},
				{km.Retry.Help().Key, "Retry failed run"},
				{km.Refresh.Help().Key, "Refresh data"},
				{km.LogView.Help().Key, "View daemon logs"},
			},
		},
		{
			Title: "Views",
			Entries: []HelpEntry{
				{km.Sources.Help().Key, "Open source manager"},
			},
		},
		{
			Title: "Global",
			Entries: []HelpEntry{
				{km.Back.Help().Key, "Return to dashboard"},
				{km.Help.Help().Key, "Toggle this help overlay"},
				{km.Quit.Help().Key, "Quit the application"},
				{km.ForceQuit.Help().Key, "Force quit immediately"},
			},
		},
	}
}

func logViewerHelp(km KeyMap) []HelpSection {
	return []HelpSection{
		{
			Title: "Navigation",
			Entries: []HelpEntry{
				{km.Up.Help().Key, "Move to previous entry"},
				{km.Down.Help().Key, "Move to next entry"},
				{km.HalfPageUp.Help().Key, "Scroll up (line-level)"},
				{km.HalfPageDown.Help().Key, "Scroll down (line-level)"},
				{km.GotoTop.Help().Key, "Jump to first entry"},
				{km.GotoBottom.Help().Key, "Jump to last entry"},
			},
		},
		{
			Title: "Expand / Collapse",
			Entries: []HelpEntry{
				{km.Open.Help().Key, "Toggle expand/collapse current entry"},
				{km.ExpandAll.Help().Key, "Expand all multi-line entries"},
				{km.CollapseAll.Help().Key, "Collapse all entries"},
			},
		},
		{
			Title: "Search",
			Entries: []HelpEntry{
				{km.Search.Help().Key, "Start search"},
				{km.SearchNext.Help().Key, "Jump to next match"},
				{km.SearchPrev.Help().Key, "Jump to previous match"},
			},
		},
		{
			Title: "View",
			Entries: []HelpEntry{
				{km.FollowToggle.Help().Key, "Toggle follow mode (auto-scroll)"},
			},
		},
		{
			Title: "Global",
			Entries: []HelpEntry{
				{km.Back.Help().Key, "Return to pipeline monitor"},
				{km.Help.Help().Key, "Toggle this help overlay"},
				{km.Quit.Help().Key, "Quit the application"},
				{km.ForceQuit.Help().Key, "Force quit immediately"},
			},
		},
	}
}
